#!/usr/bin/env zsh
# ============================================================================
# p10k project-context segment — expected-vs-active runtime status
# ============================================================================
# DISPLAY-ONLY. This segment shows the runtime version status of the current
# project. It NEVER installs, switches, or otherwise manages versions — the
# version-manager engine owns that; the prompt only reads.
#
# WHAT IT SHOWS
#   For each supported runtime (node, python, go, rust, php): the version
#   pinned by the project's pin file (.nvmrc, .python-version, .go-version,
#   .rust-toolchain, .php-version) next to the active runtime version, with
#   a match/mismatch marker. A runtime with neither a pin file nor an
#   installed tool is omitted entirely.
#
# PERFORMANCE CONTRACT
#   The per-prompt callback below only READS a small cache file. The cache
#   is regenerated by a chpwd hook (on directory change) — never per prompt
#   — by a fast zsh-native reader. The machine JSON status API of the
#   version manager is deliberately NOT invoked here: assembling JSON per
#   prompt would be far too slow.
#
# FAIL-OPEN
#   Any error (unreadable pin, unwritable cache, missing tool, missing
#   hooks) degrades to "segment renders nothing". This file can never break
#   your prompt.
#
# REGISTER (opt-in — nothing here edits your config)
#   In ~/.p10k.zsh, or better in your overrides file sourced AFTER p10k:
#
#     # 1. Source this file after p10k is loaded:
#     [[ -f <repo>/config/p10k-project-context.zsh ]] && \
#         source <repo>/config/p10k-project-context.zsh
#
#     # 2. Bind the custom segment and add it to your prompt elements:
#     typeset -g POWERLEVEL9K_CUSTOM_PROJECT_CONTEXT="vms_prompt_context"
#     typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
#         # ... your existing elements ...
#         custom_project_context
#     )
#
#   # 3. Optional tuning (defaults shown):
#     typeset -g VMS_PROMPT_CTX_MATCH_ICON="✓"
#     typeset -g VMS_PROMPT_CTX_MISMATCH_ICON="✗"
#
# CACHE LOCATION
#   ${XDG_CACHE_HOME:-$HOME/.cache}/version-manager/prompt-context
#   A handful of short lines owned by this segment; nothing else reads it.
#
# KNOWN LIMITATION
#   The cache refreshes on directory change only. Editing a pin file in
#   place does not refresh the segment until you cd out and back.
# ============================================================================

# zsh-only guard: sourcing from a POSIX shell must be a silent no-op.
if [[ -z "${ZSH_VERSION:-}" ]]; then
    return 0 2>/dev/null || true
fi

# ---- Tunables (overridable before or after sourcing) ----------------------
typeset -g VMS_PROMPT_CTX_MATCH_ICON="${VMS_PROMPT_CTX_MATCH_ICON:-✓}"
typeset -g VMS_PROMPT_CTX_MISMATCH_ICON="${VMS_PROMPT_CTX_MISMATCH_ICON:-✗}"

# Cache file (fixed location, per the documented contract).
typeset -g _VMS_PROMPT_CTX_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/version-manager/prompt-context"

# Pin file per runtime (associative: runtime -> filename).
typeset -gA _VMS_PROMPT_CTX_PINS=(
    node    .nvmrc
    python  .python-version
    go      .go-version
    rust    .rust-toolchain
    php     .php-version
)

# ---- chpwd-driven refresh (fast, zsh-native, no JSON) ----------------------
# Regenerates the cache file for the CURRENT directory. Cache line format:
#   runtime<TAB>expected<TAB>active<TAB>match-flag(1|0)
# expected/active are empty fields when the pin file / runtime is absent.
# On any write failure the stale cache is best-effort removed so the
# segment renders nothing rather than stale data.
#
# RE-ENTRANCY GUARD: this function is a chpwd hook, and chpwd fires on EVERY
# cd — including a cd inside this function's own command substitutions
# (forked subshells inherit the hook). The busy flag (inherited by forks)
# makes any nested invocation a no-op instead of an infinite fork bomb.
vms_prompt_refresh() {
    [[ -z "${_VMS_PROMPT_CTX_BUSY:-}" ]] || return 1
    typeset -g _VMS_PROMPT_CTX_BUSY=1
    _vms_prompt_refresh_do
    typeset -g _VMS_PROMPT_CTX_BUSY=""
    return 0
}

_vms_prompt_refresh_do() {
    emulate -L zsh
    setopt local_options no_err_exit nopipefail

    [[ -n "${HOME:-}" ]] || return 1
    local dir="$PWD"
    local cache="$_VMS_PROMPT_CTX_CACHE"
    # NOTE: every local is declared ONCE here, before the loop below.
    # Re-declaring an existing parameter with `local` inside a loop makes
    # zsh PRINT the parameter's current value (typeset echo behavior) —
    # that would leak stray lines into the prompt-callback stdout.
    local rt pinfile expected active raw tc
    local matchflag ne na cache_dir

    local -a lines=()
    for rt in node python go rust php; do
        pinfile="${_VMS_PROMPT_CTX_PINS[$rt]:-}"
        expected=""
        active=""

        if [[ -n "$pinfile" && -f "$dir/$pinfile" ]]; then
            raw=""
            read -r raw < "$dir/$pinfile" 2>/dev/null || true
            raw="${raw:-}"
            (( ${#raw} <= 64 )) || raw=""
            expected="$raw"
        fi

        case "$rt" in
            node)
                if (( $+commands[node] )); then
                    raw="$(node --version 2>/dev/null)" || raw=""
                    active="${raw%%$'\n'*}"
                fi
                ;;
            python)
                if (( $+commands[python3] )); then
                    raw="$(python3 --version 2>&1 | head -n1)" || raw=""
                    active="${raw#* }"
                    active="${active%%$'\n'*}"
                fi
                ;;
            go)
                if (( $+commands[go] )); then
                    raw="$(go version 2>/dev/null)" || raw=""
                    raw="${raw#go version }"
                    active="${raw%% *}"
                fi
                ;;
            rust)
                # rustup-managed rustc resolves the project's rust-toolchain
                # pin and AUTO-INSTALLS a missing toolchain (slow, networked
                # — and an install, which this display-only segment must
                # never trigger). Resolve the DEFAULT toolchain explicitly
                # instead; `rustup run` on a missing toolchain fails fast
                # and locally. No `cd` anywhere in this hook: a cd would
                # re-fire this very hook from within subshells.
                raw=""
                if (( $+commands[rustup] )); then
                    tc="$(rustup default 2>/dev/null)" || tc=""
                    tc="${tc%% *}"
                    if [[ -n "$tc" ]]; then
                        raw="$(rustup run "$tc" rustc --version 2>/dev/null)" || raw=""
                    fi
                elif (( $+commands[rustc] )); then
                    raw="$(rustc --version 2>/dev/null)" || raw=""
                fi
                active="${raw#* }"
                active="${active%% *}"
                ;;
            php)
                if (( $+commands[php] )); then
                    raw="$(php --version 2>/dev/null | head -n1)" || raw=""
                    active="${raw#* }"
                    active="${active%% *}"
                fi
                ;;
        esac

        if [[ -z "$expected" && -z "$active" ]]; then
            continue
        fi

        matchflag=0
        if [[ -n "$expected" && -n "$active" ]]; then
            ne="${expected#v}"
            ne="${ne#go}"
            na="${active#v}"
            na="${na#go}"
            if [[ "$ne" == "$na" ]]; then
                matchflag=1
            fi
        fi

        lines+=("${rt}"$'\t'"${expected}"$'\t'"${active}"$'\t'"${matchflag}")
    done

    cache_dir="${cache:h}"
    if ! mkdir -p -- "$cache_dir" 2>/dev/null; then
        command rm -f -- "$cache" 2>/dev/null
        return 1
    fi
    if (( ${#lines} )); then
        if ! print -r -- "${(F)lines}" >| "$cache" 2>/dev/null; then
            command rm -f -- "$cache" 2>/dev/null
            return 1
        fi
    else
        if ! : >| "$cache" 2>/dev/null; then
            command rm -f -- "$cache" 2>/dev/null
            return 1
        fi
    fi
    return 0
}

# ---- p10k callback: reads the cache only (fast) ----------------------------
# p10k custom segment: stdout becomes the segment content; printing nothing
# renders no segment (fail-open).
vms_prompt_context() {
    emulate -L zsh
    setopt local_options no_err_exit nopipefail

    local cache="$_VMS_PROMPT_CTX_CACHE"
    [[ -r "$cache" ]] || return 0

    local -a lines=()
    lines=("${(f)$(<"$cache")}") 2>/dev/null || lines=()

    local line rt expected active matchflag icon
    local out=""
    for line in "${lines[@]}"; do
        rt="${line%%$'\t'*}"
        case "$rt" in
            node|python|go|rust|php) ;;
            *) continue ;;
        esac
        line="${line#*$'\t'}"
        expected="${line%%$'\t'*}"
        line="${line#*$'\t'}"
        active="${line%%$'\t'*}"
        matchflag="${line#*$'\t'}"

        icon="$VMS_PROMPT_CTX_MISMATCH_ICON"
        if [[ "$matchflag" == "1" ]]; then
            icon="$VMS_PROMPT_CTX_MATCH_ICON"
        fi

        if [[ -n "$expected" && -n "$active" ]]; then
            out+="$rt:$expected→$active$icon "
        elif [[ -n "$expected" ]]; then
            out+="$rt:$expected$icon "       # pinned but not installed
        elif [[ -n "$active" ]]; then
            out+="$rt:$active "              # no pin: active is informational
        fi
    done

    out="${out% }"
    if [[ -n "$out" ]]; then
        print -r -- "$out"
    fi
    return 0
}

# ---- Hook registration (chpwd) ---------------------------------------------
if (( ! $+functions[add-zsh-hook] )); then
    autoload -Uz add-zsh-hook 2>/dev/null || true
fi
if (( $+functions[add-zsh-hook] )); then
    add-zsh-hook chpwd vms_prompt_refresh 2>/dev/null || true
    # Initial refresh for the directory the shell starts in.
    vms_prompt_refresh 2>/dev/null || true
fi

# No auto-registration of POWERLEVEL9K_CUSTOM_PROJECT_CONTEXT happens here —
# see the header for the documented, opt-in registration in your own config.
